### ISSUE TITLE
Reimplement check_linestrings

### ISSUE THREAD

**Issue by Huite** [Deltares/pandamesh#10]
Currently, the check_linestrings function checks for intersections of every entire linestring, because the mesh generators do not like crossing line segments. However, checking the entire linestrings for an intersection is too coarse of a way of doing this. Instead, each segment should be checked for intersections instead.

We should likely not do a vectorized implementation using every combination. Perhaps something along the line of:

* Gather linestring bounding boxes
* Seek intersection candidates by bounding box
* Break linestrings into segments
* Check bounding boxes for each segment
* Compute intersections

**Comment by vieirasaulo** [comment]
I have primarily been utilizing the API with Triangle during my MSc, and I wanted to say thank you excellent work. While working with it, I observed that the line string checks might be a bit too restrictive. After conducting a few manual tests, I found that by omitting these checks, we can still mesh lines that intersect. It appears that in cases where lines are almost overlapping, Triangle encounters challenges and continues to generate infinitesimally small triangles.

**Comment by vieirasaulo** [comment]
Totally agreed. Taking differences usually work well for very controlled geometries in my projects, but I haven't actively tested it for real-gis geometries. My workaround to solve that issue was:

1. Disabling LineString check-ups 
2. Applying linear referencing,
3.  Break crossing lines into smaller sub segments, as recommended in Shewchuck's website (https://www.cs.cmu.edu/~quake/triangle.trouble.html)
4. Round geometries to 32 bits of precision (~8th decimal)

This approach also worked well for nearly intersecting polygons.

Similar kind of approaches were taken by BASEmesh (https://gitlab.ethz.ch/vaw/public/basemesh-v2). I haven't checked the source code, but they use a "fuzzy snapping method" at a threshold distance.

**Comment by Huite** [comment]
Picking this up again:

* The shapely STRtree can do most of the work (it'll check bounding boxes)
* We can maximize the amount of work it does by breaking linestrings into segments before hand.
* For all overlapping bounding boxes, we can compute segment-segment intersections in a vectorized manner.
* Stuff all segment vertices into a scipy KDTree
* Find nearest vertex for each intersection (KDTree.query).
* If the distance is 0, then the intersection is represented; if it's `>0`, then it's not an existing vertex and there are unresolved intersections.

The last one is a bit difficult; due to floating point round-off intersections might be some small epsilon away instead.
I guess we can use a tolerance instead, although that's not fully secure. But the perfect is probably the enemy of the good...

Ideally we either get a warning or an error. We can report maintain an array of feature -> segment, and convert the segment-segment intersection to a feature-feature intersection, reporting the intersection coordinates as well.

**Comment by Huite** [comment]
Fairly easy to do:

```python
# %%

import shapely 
from shapely import STRtree
from scipy.spatial import KDTree
import numpy as np

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import shapely
import shapely.geometry as sg

import pandamesh as pm

# %%

def compute_intersections(segments, i, j):
    check = j > i
    i = i[check]
    j = j[check]
    seg1 = segments[i]
    seg2 = segments[j]
    
    x1, y1 = seg1[:, 0, 0], seg1[:, 0, 1]
    x2, y2 = seg1[:, 1, 0], seg1[:, 1, 1]
    x3, y3 = seg2[:, 0, 0], seg2[:, 0, 1]
    x4, y4 = seg2[:, 1, 0], seg2[:, 1, 1]
    
    den = (y4 - y3) * (x2 - x1) - (x4 - x3) * (y2 - y1)
    num1 = (x4 - x3) * (y1 - y3) - (y4 - y3) * (x1 - x3)
    num2 = (x2 - x1) * (y1 - y3) - (y2 - y1) * (x1 - x3)
    
    mask = np.abs(den) > 1e-8  # Filter out parallel lines
    t = np.zeros_like(den)
    u = np.zeros_like(den)
    t[mask] = num1[mask] / den[mask]
    u[mask] = num2[mask] / den[mask]
    
    intersect_mask = (0 <= t) & (t <= 1) & (0 <= u) & (u <= 1)
    x = x1 + t * (x2 - x1)
    y = y1 + t * (y2 - y1)
    
    return np.column_stack((x[intersect_mask], y[intersect_mask]))


def check_linework_intersections(gdf: gpd.GeoDataFrame, upper_search_bound=10.0, tolerance=1.0e-6):
    polygons, lines, _ = pm.common.separate_geometry(gdf.geometry)
    outer_rings = polygons.exterior
    inner_rings = np.array(pm.common.flatten(polygons.interiors))
    linework = np.concatenate((lines, outer_rings, inner_rings))

    coordinates, index = shapely.get_coordinates(linework, return_index=True)
    segments = np.stack((coordinates[:-1, :], coordinates[1:]), axis=1)
    keep = np.diff(index) == 0
    segments = segments[keep]
    segment_linestrings = shapely.linestrings(segments.reshape((-1, 2)), indices=np.repeat(np.arange(len(segments)), 2))

    rtree = STRtree(segment_linestrings)
    i, j = rtree.query(segment_linestrings)
    intersections = compute_intersections(segments, i, j)

    vertices = np.unique(coordinates, axis=0)
    kdtree = KDTree(vertices)
    distance, index = kdtree.query(intersections, distance_upper_bound=upper_search_bound)

    return intersections[distance > tolerance]


# %%

donut = sg.Polygon(
    [
        [0.0, 0.0],
        [10.0, 0.0],
        [10.0, 10.0],
        [0.0, 10.0],
    ],
    holes=[
        [
            [2.0, 5.0],
            [5.0, 8.0],
            [8.0, 5.0],
            [5.0, 2.0],
        ]
    ],
)
line0 = shapely.LineString(
    [
        [-2.0, 0.0],
        [12.0, 10.0],
    ]
)
line1 = shapely.LineString(
    [
        [5.5, 9.0],
        [9.0, 5.5],
    ]
)
gdf = gpd.GeoDataFrame(geometry=[donut, line0, line1])

# %%

locations = check_linework_intersections(gdf)
fig, ax = plt.subplots()
gdf.plot(ax=ax, facecolor="none")
ax.scatter(*locations.T)
```

![image](https://github.com/user-attachments/assets/25d3c2c4-0766-46f8-ab14-4067fa0ffbe1)

And as expected, the preprocessor ensures the intersection vertices are present, and no unresolved intersections are found:

```python
new = (
    pm.Preprocessor(geometry=gdf.geometry)
    .unify_polygons()
    .merge_polygons()
    .unify_lines()
    .to_geodataframe()
)

new_locations = check_linework_intersections(new)
fig, ax = plt.subplots()
gdf.plot(ax=ax, facecolor="none")
ax.scatter(*new_locations.T)
```

![image](https://github.com/user-attachments/assets/2fabe992-411f-4393-bd6e-49c77be620fa)

**Comment by Huite** [comment]
Still a bit unsure about the upper_search_bound -- I guess it can be really quite small -- and the tolerance is floating point dependent, but should be zero often because any resolved intersection will probably have been computed in almost exactly the same manner.

By default it might be smart to error if `len(intersections) > 0`, with maybe a flag with `{"error", "warn", "ignore"}`.
Printing the locations seems like it would be probably be the most helpful, rather than showing indices. Also a suggestion to run the preprocessor thing.
