### ISSUE TITLE
 gmsh report error "signal only works in main thread of the main interpreter"

### ISSUE THREAD

**Issue by remi-braun** [Deltares/pandamesh#13]
Hello,

I am trying to use pandamesh in a script called by ArcGIS Pro.
It results on a `ValueError`: `signal only works in main thread of the main interpreter` 

![2024-02-02_11h03_08](https://github.com/Deltares/pandamesh/assets/67311115/fcc89107-f448-4f8d-a167-33109ad73e8c)

The same script works fine when run from the terminal though.

Maybe linked to the same issue than : https://github.com/nschloe/pygmsh/issues/520

Maybe handling this importing error from `gmsh` would allow users to work in this type of environment with TriangleMesher?

**Comment by remi-braun** [comment]
Yes I think your diagnostic is correct.

I am currently testing your solution and it seems to work :)

**Comment by Huite** [comment]
So I've been able to reproduce it, and this'll work in a standalone test:

```python
import threading
from queue import Queue


def run_import() -> bool:
    try:
        from pandamesh.common import gmsh
    except Exception:
        return False

    if not gmsh.ok and isinstance(gmsh.error, RuntimeError):
        return True
    else:
        return False


def test_import_threaded_gmsh():
    que = Queue()
    thread = threading.Thread(target=lambda q: q.put(run_import()), args=(que,))
    thread.start()
    thread.join()
    result = que.get()
    assert result
```

The problem is that in normal pytest use, pytest already has imported the thing, and so the problem doesn't trigger since Python skips imports of already imported packages.

I've seen it work locally, and along with your remark it's good enough for me now...

**Comment by remi-braun** [comment]
I maybe have found a workaround to avoid triggering "signal" on gmesh initialization.

I just added `interruptible=False` in `_initialize_gmsh`

```python
    @staticmethod
    def _initialize_gmsh():
        GmshMesher.finalize_gmsh()
        gmsh.initialize(interruptible=False)
        gmsh.option.setNumber("General.Terminal", 1)
```

It could be great to let people initialize gmsh with some kwargs :)

**Comment by Huite** [comment]
Excellent suggestion! I'll open an issue.
