### ISSUE TITLE
DOC: Add somewhere to document releases

### ISSUE THREAD

**Issue by remi-braun** [Deltares/pandamesh#14]
Hi,

It would be great to have somewhere a way to see when new releases are done and what are in it.
For example, a `CHANGES.md` file would be great!

Thanks a lot 😄

**Comment by Huite** [comment]
I agree, was hoping to make a release and add a changelog, but didn't manage on Friday.

I'll try and get it out today (PyPI that is, conda-forge always needs a bit more time).

**Comment by Huite** [comment]
Finally got a pypi-release: https://pypi.org/project/pandamesh/0.1.4/

Changelog can be found via the API reference:
https://deltares.github.io/pandamesh/api/changelog.html

**Comment by remi-braun** [comment]
Very nice of you tu update and take suggetions as quickly as that 😄
