### ISSUE TITLE
Pandamesh typing fails with Python 3.9

### ISSUE THREAD

**Issue by remi-braun** [Deltares/pandamesh#16]
Hello,

It's me again 😅 

You have some typing that fails with Python3.9:

![2024-02-06_08h55_30](https://github.com/Deltares/pandamesh/assets/67311115/a2ca32c3-a482-4733-b204-5d40d38ae431)

However, in pypi, you still say Python 3.9 is handled. 
It should then be replaced by `Union[Enum, IntEnum]`.

I would be very grateful if you could backport those typing to 3.9 🙏 
If you don't intend to do so, please discard 3.9 version from last package 😉

**Comment by Huite** [comment]
Sigh, I could've known! Thanks for reporting!

`from future import __annotations__` also does the trick for Python 3.9. Should've checked that.

I think I'll add multiple python version testing to the CI, and I'll pull the release from pypi.

**Comment by Huite** [comment]
I've yanked 0.1.4, released a new version 0.1.5, and I've added tests for python 3.9 and 3.10 explicitly. Thanks for hanging in there!
