### ISSUE TITLE
Compatibility with Numpy 2.0.0 

### ISSUE THREAD

**Issue by HeiJuli** [Deltares/pandamesh#24]
Hi, 

I just wanted to ask whether you are working on a compatibility with Numpy 2.0.0? If so, when could I expect a solution? We have `pandamesh` as a dependency in our project and would like to work with the latest numpy package.

**Comment by HeiJuli** [comment]
create a short fix for myself to be compatible with numpy 2.0.0, you can see changes here: https://github.com/Deltares/pandamesh/compare/main...HeiJuli:pandamesh:fix_numpy2. They are related to the array structure of the segments returned from numpy.unique() ...

But I am sure more changes are required for full compatibility.

**Comment by Huite** [comment]
Hi @HeiJuli,

Thanks for opening this issue! I've been looking at other packages for the numpy 2.0 compat.
I did a brief test for pandamesh, saw some failures and feared the worst -- namely that the triangle bindings might not work anymore either.

Your post here prompted me to take a better look, it seems like everything is pretty much okay; raveling the unique `inverse` and a deprecation in the test seems to do the trick. The generated docs seem to look normal too, so neither the Triangle nor the Gmsh bindings seem to have broken.

I've submitted a PR just now.

If you'd like, you could do a checkout of main and verify that everything works on your end as well -- I can make a new release then.

**Comment by HeiJuli** [comment]
Perfect, thanks a lot for you quick response and quick fix! 

I tested it, and it looks good!

**Comment by Huite** [comment]
Hi @HeiJuli, I've just released 0.1.6 on pypi, conda-forge release will follow soon.

**Comment by HeiJuli** [comment]
amazing, thanks for the quick release!
